name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          echo "Releasing $GITHUB_REF_NAME"
          gh release create $GITHUB_REF_NAME --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
